"""
Translation of a Django EmailMessage into the JSON message resource of Graph.

The Microsoft Graph API accepts an email either as base64 encoded MIME content
or as a JSON `message` resource. Django builds MIME messages, so the backend
sends MIME by default. This module provides the alternative: it maps the parts
of an EmailMessage that Graph can express in JSON onto that resource.

The mapping is intentionally explicit rather than a MIME parser. Everything
that Graph generates on its own, such as the Date and Message-ID headers, or
that JSON cannot express, such as a plain text alternative next to an HTML
body, is left to Graph and documented in the README.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from email.utils import getaddresses
from typing import TYPE_CHECKING

from .attachments import iter_attachments

if TYPE_CHECKING:
    from collections.abc import Iterable

    from django.core.mail.message import EmailMessage


logger = logging.getLogger(__name__)

# Graph only lets a message carry custom Internet message headers whose name
# starts with this prefix. Every other header is either a property of the
# message resource or generated by Exchange.
CUSTOM_HEADER_PREFIX = "x-"


def sendmail_payload(
    email_message: EmailMessage,
    *,
    save_to_sent_items: bool = True,
) -> dict:
    """
    Returns the request body of the sendMail action for an EmailMessage.

    The attachments travel inside the message, so this payload is only suited
    for a message that fits into a single request.
    """
    payload: dict = {"message": graph_message(email_message)}
    if not save_to_sent_items:
        # Graph defaults to saving the message and asks to send the parameter
        # only when it is false.
        payload["saveToSentItems"] = False
    return payload


def graph_message(
    email_message: EmailMessage, *, with_attachments: bool = True
) -> dict:
    """
    Returns the Graph message resource that represents an EmailMessage.

    Without its attachments, the resource is what creates the draft of a large
    message, to which the attachments are then uploaded separately.
    """
    headers = _split_headers(email_message)
    message: dict = {
        "subject": email_message.subject,
        "body": _body(email_message),
        "toRecipients": _recipients(email_message.to),
    }
    sender = _recipients([headers.sender or email_message.from_email])
    if sender:
        message["from"] = sender[0]
    if email_message.cc:
        message["ccRecipients"] = _recipients(email_message.cc)
    if email_message.bcc:
        message["bccRecipients"] = _recipients(email_message.bcc)
    reply_to = _recipients(
        [headers.reply_to] if headers.reply_to else email_message.reply_to
    )
    if reply_to:
        message["replyTo"] = reply_to
    if headers.custom:
        message["internetMessageHeaders"] = headers.custom
    if with_attachments and email_message.attachments:
        message["attachments"] = [
            attachment.as_file_attachment()
            for attachment in iter_attachments(email_message)
        ]
    return message


def _body(email_message: EmailMessage) -> dict:
    """
    Returns the itemBody of the message.

    Graph holds a single body, so the HTML alternative of an
    EmailMultiAlternatives wins over its plain text, which Graph derives from
    the HTML on its own. A plain EmailMessage whose content_subtype is html
    is sent as HTML as well.
    """
    if email_message.content_subtype == "html":
        return {"contentType": "html", "content": email_message.body}
    for content, mimetype in getattr(email_message, "alternatives", ()):
        if mimetype == "text/html":
            return {"contentType": "html", "content": content}
    return {"contentType": "text", "content": email_message.body}


def _recipients(addresses: Iterable[str]) -> list[dict]:
    """
    Returns the recipient resources for a list of addresses.

    Django accepts an address either bare or as `Name <address>`, and a header
    value may hold several of them. The display name travels as is, because
    JSON does not need the RFC 2047 encoding that MIME would apply.
    """
    recipients = []
    for name, address in getaddresses([str(value) for value in addresses if value]):
        if not address:
            continue
        email_address: dict = {"address": address}
        if name:
            email_address["name"] = name
        recipients.append({"emailAddress": email_address})
    return recipients


@dataclass
class _Headers:
    """The extra headers of a message, sorted by what Graph makes of them."""

    sender: str | None = None
    reply_to: str | None = None
    custom: list[dict] = field(default_factory=list)


def _split_headers(email_message: EmailMessage) -> _Headers:
    """
    Sorts the extra headers of the message by how the JSON format carries them.

    Django lets a From or Reply-To header override the respective attribute of
    the message, so both become properties of the resource. A custom header,
    which Graph only accepts with the x- prefix, keeps its name and value.
    Every other header is dropped with a warning instead of failing the whole
    message, because the standard headers are either properties of the
    resource or set by Exchange, so that a Django project switching to the JSON
    format keeps sending emails.
    """
    headers = _Headers()
    for name, value in email_message.extra_headers.items():
        name, value = str(name), str(value)
        lowercase_name = name.lower()
        if lowercase_name == "from":
            headers.sender = value
        elif lowercase_name == "reply-to":
            headers.reply_to = value
        elif lowercase_name.startswith(CUSTOM_HEADER_PREFIX):
            headers.custom.append({"name": name, "value": value})
        else:
            logger.warning(
                "The header '%s' is dropped, because the JSON format of the "
                "Microsoft Graph API only accepts custom headers starting with "
                "'x-'. Use the MIME format to send it.",
                name,
            )
    return headers
